server:
  port: 8787
  servlet:
    context-path: /fileconverterrest
spring:
  application:
    name: file-format-converter
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB     
